"""Added verification_code to Order model

Revision ID: 16586d2503a3
Revises: 944d7299303c
Create Date: 2023-07-01 12:01:41.308979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16586d2503a3'
down_revision = '944d7299303c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('license_plate', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('displacement', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('displacement')
        batch_op.drop_column('color')
        batch_op.drop_column('license_plate')
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
