"""Added role to User

Revision ID: 944d7299303c
Revises: ec77e396693b
Create Date: 2023-06-29 16:44:40.457067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944d7299303c'
down_revision = 'ec77e396693b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
