"""Added verification_code to Order model

Revision ID: ec77e396693b
Revises: c80842b5f14f
Create Date: 2023-06-27 16:27:11.343511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec77e396693b'
down_revision = 'c80842b5f14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
