"""Added return_status and is_returned to orders

Revision ID: ff1d1b58c911
Revises: 16586d2503a3
Create Date: 2023-07-04 22:02:55.019972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1d1b58c911'
down_revision = '16586d2503a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_returned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rented', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('is_rented')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('is_returned')
        batch_op.drop_column('return_status')

    # ### end Alembic commands ###
